import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion } from 'framer-motion';
import { Activity, ArrowUpRight, Bell, BusFront, ChevronRight, CircleHelp, Clock3, Fuel, Gauge, LayoutDashboard, Menu, Search, Settings2, ShieldCheck, Sparkles, Users, Wrench, X, Zap } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

type Metric = { key: string; label: string; value: string; change: string; tone: 'good' | 'warn' | 'bad'; icon: React.ElementType; description: string };
type Base = { name: string; code: string; services: number; fleet: number; punctuality: number; people: number; alerts: number; color: string };

const bases: Base[] = [
  { name: 'Córdoba', code: 'COR', services: 97.2, fleet: 92.4, punctuality: 96.5, people: 3.8, alerts: 2, color: '#8b5cf6' },
  { name: 'Comodoro', code: 'COM', services: 91.5, fleet: 84.1, punctuality: 90.3, people: 7.1, alerts: 5, color: '#22d3ee' },
  { name: 'San Luis', code: 'SLU', services: 95.4, fleet: 89.8, punctuality: 94.2, people: 4.6, alerts: 3, color: '#34d399' },
  { name: 'Villa Mercedes', code: 'VME', services: 93.1, fleet: 81.7, punctuality: 89.8, people: 5.4, alerts: 6, color: '#f59e0b' },
];

const traffic = [
  { time: '06:00', value: 82 }, { time: '08:00', value: 94 }, { time: '10:00', value: 88 }, { time: '12:00', value: 91 },
  { time: '14:00', value: 86 }, { time: '16:00', value: 96 }, { time: '18:00', value: 99 }, { time: '20:00', value: 93 },
];
const distribution = [{ name: 'Operativa', value: 84, color: '#8b5cf6' }, { name: 'En taller', value: 10, color: '#f59e0b' }, { name: 'Fuera de servicio', value: 6, color: '#fb7185' }];
const navItems = [{ label: 'Resumen', icon: LayoutDashboard }, { label: 'Tráfico', icon: Activity }, { label: 'Flota', icon: BusFront }, { label: 'Taller', icon: Wrench }, { label: 'RRHH', icon: Users }];

function App() {
  const [activeNav, setActiveNav] = useState('Resumen');
  const [selectedBase, setSelectedBase] = useState<Base | null>(null);
  const [period, setPeriod] = useState('Hoy');
  const [query, setQuery] = useState('');
  const [mobileNav, setMobileNav] = useState(false);

  const filteredBases = useMemo(() => bases.filter((base) => base.name.toLowerCase().includes(query.toLowerCase())), [query]);
  const metrics: Metric[] = [
    { key: 'services', label: 'Servicios cumplidos', value: '94,8%', change: '+2,4%', tone: 'good', icon: Gauge, description: 'vs. objetivo 92%' },
    { key: 'fleet', label: 'Flota disponible', value: '88,5%', change: '-1,8%', tone: 'warn', icon: BusFront, description: '326 unidades activas' },
    { key: 'passengers', label: 'Pasajeros transportados', value: '373.000', change: '+6,3%', tone: 'good', icon: Users, description: 'en las 4 bases' },
    { key: 'punctuality', label: 'Puntualidad', value: '92,7%', change: '+1,1%', tone: 'good', icon: Clock3, description: 'demora media 4 min' },
  ];

  return <div className="app-shell">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>pulse<span>ops</span></span></div>
      <div className="workspace"><span className="workspace-dot" /> Grupo Transporte <ChevronRight size={14} /></div>
      <p className="nav-title">Workspace</p>
      <nav>{navItems.map((item) => <button className={activeNav === item.label ? 'nav-item active' : 'nav-item'} onClick={() => { setActiveNav(item.label); setMobileNav(false); }} key={item.label}><item.icon size={18} /><span>{item.label}</span>{item.label === 'Resumen' && <span className="live-dot" />}</button>)}</nav>
      <p className="nav-title second">Gestión</p>
      <nav><button className="nav-item"><Fuel size={18} /><span>Combustible</span></button><button className="nav-item"><ShieldCheck size={18} /><span>Seguridad</span></button><button className="nav-item"><Settings2 size={18} /><span>Configuración</span></button></nav>
      <div className="sidebar-bottom"><div className="help"><CircleHelp size={17} /><div><strong>¿Necesitas ayuda?</strong><span>Centro de soporte</span></div></div><div className="user"><div className="avatar">LV</div><div><strong>Leo Videla</strong><span>Gerente general</span></div><ChevronRight size={15} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="icon-button menu-button" onClick={() => setMobileNav(!mobileNav)}><Menu size={20} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><strong>{activeNav}</strong></div><div className="top-actions"><div className="search"><Search size={16} /><input placeholder="Buscar base, línea o vehículo..." value={query} onChange={(e) => setQuery(e.target.value)} /></div><button className="icon-button notification"><Bell size={18} /><i /></button><div className="top-avatar">LV</div></div></header>
      <section className="hero"><div><div className="eyebrow"><span className="status-pulse" /> Operación en vivo <span className="separator">·</span> Actualizado hace 2 min</div><h1>Buen día, Leo <span>✦</span></h1><p>Una mirada inteligente sobre toda tu operación.</p></div><div className="hero-actions"><div className="period-switcher">{['Hoy', '7 días', '30 días'].map((item) => <button className={period === item ? 'selected' : ''} onClick={() => setPeriod(item)} key={item}>{item}</button>)}</div><button className="export-button"><ArrowUpRight size={16} /> Exportar</button></div></section>
      <section className="metrics-grid">{metrics.map((metric, index) => <motion.button initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .07 }} whileHover={{ y: -4 }} className="metric-card" key={metric.key} onClick={() => setActiveNav(metric.label)}><div className="metric-top"><span className="metric-icon"><metric.icon size={18} /></span><span className={`change ${metric.tone}`}>{metric.change}</span></div><span className="metric-label">{metric.label}</span><strong>{metric.value}</strong><span className="metric-description">{metric.description}<ArrowUpRight size={13} /></span></motion.button>)}</section>
      <section className="dashboard-grid"><motion.div className="panel chart-panel" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .35 }}><div className="panel-heading"><div><span className="section-kicker">Rendimiento operativo</span><h2>El pulso de tu servicio</h2></div><button className="more-button">Últimas 24 h <ChevronRight size={15} /></button></div><div className="chart-legend"><span><i className="legend-purple" /> Cumplimiento</span><span><i className="legend-cyan" /> Meta 92%</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={traffic}><defs><linearGradient id="pulseGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.35} /><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(255,255,255,.06)" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fill: '#7f8aa3', fontSize: 11 }} /><YAxis domain={[70, 105]} axisLine={false} tickLine={false} tick={{ fill: '#7f8aa3', fontSize: 11 }} tickFormatter={(v) => `${v}%`} /><Tooltip contentStyle={{ background: '#151a2b', border: '1px solid rgba(255,255,255,.1)', borderRadius: 12, color: '#fff' }} formatter={(v) => [`${v}%`, 'Cumplimiento']} /><Area type="monotone" dataKey="value" stroke="#a78bfa" strokeWidth={3} fill="url(#pulseGradient)" dot={false} activeDot={{ r: 5, fill: '#fff', stroke: '#8b5cf6', strokeWidth: 3 }} /></AreaChart></ResponsiveContainer></div></motion.div>
      <motion.div className="panel fleet-panel" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .45 }}><div className="panel-heading"><div><span className="section-kicker">Disponibilidad</span><h2>Estado de flota</h2></div><button className="round-action"><ArrowUpRight size={16} /></button></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} innerRadius={67} outerRadius={88} paddingAngle={4} dataKey="value" stroke="none" startAngle={90} endAngle={-270}>{distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><strong>326</strong><span>unidades</span></div></div><div className="distribution-list">{distribution.map((item) => <div className="distribution-item" key={item.name}><span><i style={{ background: item.color }} />{item.name}</span><strong>{item.value}%</strong></div>)}</div></motion.div></section>
      <section className="section-header"><div><span className="section-kicker">Visión por ubicación</span><h2>Las bases operativas</h2></div><button className="text-button">Ver comparativa <ArrowUpRight size={15} /></button></section>
      <section className="base-grid">{filteredBases.map((base, index) => <motion.button layout whileHover={{ y: -5 }} transition={{ type: 'spring', stiffness: 300, damping: 20 }} className="base-card" key={base.code} onClick={() => setSelectedBase(base)}><div className="base-glow" style={{ background: base.color }} /><div className="base-card-top"><div className="base-symbol" style={{ color: base.color, borderColor: `${base.color}55` }}>{base.code}</div><span className={base.alerts > 4 ? 'alert-count warning' : 'alert-count'}><Zap size={12} /> {base.alerts} alertas</span></div><h3>{base.name}</h3><div className="base-main-stat"><strong>{base.services.toFixed(1).replace('.', ',')}%</strong><span>servicio cumplido</span></div><div className="base-mini-stats"><span>Flota <b>{base.fleet}%</b></span><span>Puntualidad <b>{base.punctuality}%</b></span></div><div className="base-progress"><div style={{ width: `${base.services}%`, background: base.color }} /></div><div className="base-footer"><span>Ver detalle de base</span><ChevronRight size={16} /></div></motion.button>)}</section>
      <section className="bottom-row"><div className="panel alert-panel"><div className="panel-heading"><div><span className="section-kicker">Requieren atención</span><h2>Alertas prioritarias</h2></div><span className="alert-badge">6 activas</span></div>{['Vehículo 342 detenido · Villa Mercedes', '3 servicios cancelados · Comodoro', '12 licencias próximas a vencer'].map((alert, index) => <div className="alert-row" key={alert}><span className={`alert-marker marker-${index}`}><Zap size={14} /></span><span>{alert}</span><ChevronRight size={15} /></div>)}</div><div className="panel insight-panel"><div className="insight-icon"><Sparkles size={18} /></div><span className="section-kicker">Pulse insight</span><h2>Una oportunidad detectada</h2><p>Villa Mercedes mejoró su puntualidad <strong>+4,8%</strong> esta semana. El turno tarde es el principal impulsor.</p><button className="insight-button">Explorar señal <ArrowUpRight size={15} /></button></div></section>
    </main>
    <AnimatePresence>{selectedBase && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedBase(null)}><motion.aside className="detail-drawer" initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 28 }} onClick={(e) => e.stopPropagation()}><div className="drawer-header"><div><span className="section-kicker">Base operativa · {selectedBase.code}</span><h2>{selectedBase.name}</h2></div><button className="icon-button" onClick={() => setSelectedBase(null)}><X size={19} /></button></div><div className="drawer-score"><span>Índice de servicio</span><strong>{selectedBase.services}%</strong><div className="score-line"><div style={{ width: `${selectedBase.services}%` }} /></div><small>+2,4% vs. período anterior</small></div><div className="drawer-kpis"><div><BusFront size={17} /><span>Flota activa</span><strong>{selectedBase.fleet}%</strong></div><div><Clock3 size={17} /><span>Puntualidad</span><strong>{selectedBase.punctuality}%</strong></div><div><Users size={17} /><span>Ausentismo</span><strong>{selectedBase.people}%</strong></div><div><Bell size={17} /><span>Alertas</span><strong>{selectedBase.alerts}</strong></div></div><div className="drawer-section"><div className="panel-heading"><h3>Actividad reciente</h3><button className="more-button">Ver todo</button></div>{['Línea 21 completó recorrido', 'Mantenimiento preventivo iniciado', 'Turno mañana cerrado'].map((item, i) => <div className="timeline" key={item}><span className={`timeline-dot dot-${i}`} /><div><strong>{item}</strong><small>{i + 1} hora{i ? 's' : ''} atrás · Operación</small></div></div>)}</div><button className="drawer-cta" onClick={() => { setActiveNav('Tráfico'); setSelectedBase(null); }}>Abrir tablero de {selectedBase.name} <ArrowUpRight size={16} /></button></motion.aside></motion.div>}</AnimatePresence>
  </div>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
